### ISSUE TITLE
Project Info Section

### ISSUE THREAD

**Issue by MalakyePierre** [eternity-software/Dira#12]
Hello, I really like the idea of this messenger and am very interested to see how it turns out. If I could, I would like to recommend changing the description of the project to make it more clear to anyone who comes across it. when I first came across the project it caught my eye a little bit but it was only after I looked more into it that I got more intrigued. I feel like this description would make it a little more clear and more eye-catching from the jump, let me know if I am wrong, and thank you for taking the time to read and consider this: 
Independent, open-source, and privacy-guaranteed messenger. No account registration necessary. Create your own private server for whatever you need

**Comment by karlovm** [comment]
Hello! Thanks for the feedback, if you have specific suggestions on how to improve the description, send a pull request with your ideas. Our team will be happy to accept your improvements.

**Comment by karlovm** [comment]
If you want, you can give us a star, it will be very nice :)
