### ISSUE TITLE
Inconsistency in RoomInfoActivity

### ISSUE THREAD

**Issue by karlovm** [eternity-software/Dira#13]
1. Open old room 
2. Face `java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positionViewHolder{821304a position=39 id=-1, oldPos=0, pLpos:0 scrap [attachedScrap] tmpDetached no parent} androidx.recyclerview.widget.RecyclerView{47a561c VFED..... ......ID 0,0-1220,1950 #7f09014b app:id/grid_view}, adapter:com.diraapp.ui.adapters.MediaGridAdapter@3fb6225, layout:androidx.recyclerview.widget.GridLayoutManager@78e3ffa, context:com.diraapp.ui.activities.RoomInfoActivity@b89cc7d`
3. App crashed :(

**Comment by danyachka** [comment]
Solved in commit 3f9573e
